### ISSUE TITLE
后台报错，web控制台提示undefined

### ISSUE THREAD

**Issue by 19819068211** [Samueli924/chaoxing_web#1]
作者大大，提交课程后提示undefined，后台报错视频任务添加失败
![屏幕截图(62)](https://user-images.githubusercontent.com/66981884/157671100-b9e7c47d-5e13-48f0-b4f6-f05db6475303.png)
![屏幕截图(63)](https://user-images.githubusercontent.com/66981884/157671125-fc7132e1-50bf-4d2f-bc68-a9dfd3f0520e.png)

**Comment by Samueli924** [comment]
请使用[Core核心库](https://github.com/Samueli924/chaoxing)  
后续内容将在核心库更新
