### ISSUE TITLE
一直无响应

### ISSUE THREAD

**Issue by d4renk** [Samueli924/chaoxing_web#2]
* Running on http://192.168.0.112:7777/ (Press CTRL+C to quit)
127.0.0.1 - - [13/Mar/2022 11:36:57] "GET / HTTP/1.0" 302 -
127.0.0.1 - - [13/Mar/2022 11:45:49] "GET / HTTP/1.0" 302 -

**Comment by Samueli924** [comment]
请使用[Core核心库](https://github.com/Samueli924/chaoxing)  
后续内容将在核心库更新
